name: Build and test

on: [push]

jobs:
  ubuntu:
    container: 
      image: swift:latest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Swift build
      run: swift build -c release
      
    - name: Test
      run: swift test --enable-test-discovery --sanitize=thread
       
    - name: Done
      run: echo Done
      
  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Test
      run: swift test --enable-test-discovery --sanitize=thread
      
    - name: Swift build
      run: swift build -c release
            
    - name: Print Swift version
      run: swift --version
      
    - name: Create XCFramework
      uses: unsignedapps/swift-create-xcframework@v2
