name: Build and test

on: [push]

jobs:
  ubuntu:
    container: 
      image: vapor/swift:5.2-bionic
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Test
      run: swift test --enable-test-discovery --sanitize=thread
      
    - name: Swift build
      run: swift build -c release
            
    - name: Done
      run: echo Done
